### ISSUE TITLE
windows bug

### ISSUE THREAD

**Issue by quasiperfect** [dmhendricks/wordpress-toolkit#1]
this https://github.com/dmhendricks/wordpress-toolkit/blob/cf4e2aa8938b08bcb791f6c4e59243c18a9ba926/core/ToolKit.php#L93
doesn't work on windows because the key is returned like 
folder/file.php and the separator is \

so the path gets the extra folder

D:\.....\plugins\folder/folder/file.php

**Comment by dmhendricks** [comment]
Thank you for reporting! I apologies for the delay - it has been busy. New release created.
